apiVersion: v1
kind: Service
metadata:
  name: virtualcluster-api
  namespace: virtualcluster-system
  labels:
    app: virtualcluster-api
spec:
  selector:
    app: virtualcluster-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080